---
name: Echo Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, DevOps!"
      - name: Multi line step
        run: |
          pwd
